version: '3'

services:
  housecall:
    ports:
      - '3001:3000'
    container_name: housecall
    image: housecall
    environment:
      - NEXT_PUBLIC_PREFIX_URL=
      - NEXT_PUBLIC_API_URL=https://https://api-corp-hc-services.bumame.com
