import type { NextPage } from 'next';
import Head from 'next/head';
import Login from './Auth/Login';

const Home: NextPage = () => {
  return (
    <div className='flex flex-col h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Login */}
      <Login />

      {/* Dashboard */}
      {/* <div className='m-auto'>
        <h1>Hello World 👋!!!</h1>
      </div> */}
    </div>
  );
};

export default Home;
