export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';
export const AUTH_LOGIN_STATUS = 'AUTH_LOGIN_STATUS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CURRENT_LOGIN_USER = 'AUTH_CURRENT_LOGIN_USER';
