export const CORPORATE_TRX_FETCH_DATATABLE = 'CORPORATE_TRX_FETCH_DATATABLE';
export const CORPORATE_TRX_FETCH_DETAIL = 'CORPORATE_TRX_FETCH_DETAIL';
export const CORPORATE_TRX_FETCH_PAYMENT_CODE =
  'CORPORATE_TRX_FETCH_PAYMENT_CODE';
export const CORPORATE_TRX_FETCH_DOCUMENT = 'CORPORATE_TRX_FETCH_DOCUMENT';
export const CORPORATE_TRX_ALERT = 'CORPORATE_TRX_ALERT';
