export const CORPORATE_FETCH_SELECT_LIST = 'CORPORATE_FETCH_SELECT_LIST';
export const CORPORATE_FETCH_DATATABLE = 'CORPORATE_FETCH_DATATABLE';
export const CORPORATE_FETCH_DETAIL = 'CORPORATE_FETCH_DETAIL';
export const CORPORATE_ALERT = 'CORPORATE_ALERT';
