export const HOUSECALL_FETCH_DATATABLE = 'HOUSECALL_FETCH_DATATABLE';
export const HOUSECALL_FETCH_TRANSACTION_ITEM =
  'HOUSECALL_FETCH_TRANSACTION_ITEM';
export const HOUSECALL_FETCH_DETAIL = 'HOUSECALL_FETCH_DETAIL';
export const HOUSECALL_ALERT = 'HOUSECALL_ALERT';
