export const LAB_TRANSACTION_FETCH_DATATABLE =
  'LAB_TRANSACTION_FETCH_DATATABLE';
export const LAB_TRANSACTION_FETCH_DETAIL = 'LAB_TRANSACTION_FETCH_DETAIL';
export const LAB_TRANSACTION_ALERT = 'LAB_TRANSACTION_ALERT';
export const LAB_TRANSACTION_CREATE = 'LAB_TRANSACTION_CREATE';
export const LAB_PARTNER_FETCH_SELECT_LIST = 'LAB_PARTNER_FETCH_SELECT_LIST';
