export const PRODUCT_FETCH_SELECT_LIST = 'PRODUCT_FETCH_SELECT_LIST';
export const PRODUCT_FETCH_COVID_SELECT_LIST =
  'PRODUCT_FETCH_COVID_SELECT_LIST';
export const PRODUCT_FETCH_MCU_SELECT_LIST = 'PRODUCT_FETCH_MCU_SELECT_LIST';
export const PRODUCT_FETCH_TIER_SELECT_LIST = 'PRODUCT_FETCH_TIER_SELECT_LIST';
export const PRODUCT_ALERT = 'PRODUCT_ALERT';
