export const ROLE_FETCH_DATATABLE = 'ROLE_FETCH_DATATABLE';
export const ROLE_FETCH_SELECT_LIST = 'ROLE_FETCH_SELECT_LIST';
export const ROLE_FETCH_SELECT_LIST_ROLE_TYPE =
  'ROLE_FETCH_SELECT_LIST_ROLE_TYPE';
export const ROLE_FETCH_EXTENSION_STATUS_DATA =
  'ROLE_FETCH_EXTENSION_STATUS_DATA';
export const ROLE_FETCH_DETAIL = 'ROLE_FETCH_DETAIL';
export const ROLE_FETCH_ACCESS_MODULES = 'ROLE_FETCH_ACCESS_MODULES';
export const ROLE_ALERT = 'ROLE_ALERT';
export const ROLE_CREATE = 'ROLE_CREATE';
export const ROLE_UPDATE = 'ROLE_UPDATE';
export const ROLE_DELETE = 'ROLE_DELETE';
