export const TRANSACTION_FETCH_DATATABLE = 'TRANSACTION_FETCH_DATATABLE';
export const TRANSACTION_FETCH_IN_HOUSE_DETAIL =
  'TRANSACTION_FETCH_IN_HOUSE_DETAIL';
export const TRANSACTION_FETCH_HOUSE_CALL_DETAIL =
  'TRANSACTION_FETCH_HOUSE_CALL_DETAIL';
export const TRANSACTION_FETCH_ITEMS = 'TRANSACTION_FETCH_ITEMS';
export const TRANSACTION_FETCH_DOCUMENT_LIST =
  'TRANSACTION_FETCH_DOCUMENT_LIST';
export const TRANSACTION_FETCH_DOCUMENT_DETAIL =
  'TRANSACTION_FETCH_DOCUMENT_DETAIL';
export const TRANSACTION_ALERT = 'TRANSACTION_ALERT';
